# Generated by Django 2.1.4 on 2019-01-20 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedRide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carsize', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_email', models.EmailField(max_length=254)),
                ('destination', models.TextField()),
                ('hour', models.TimeField()),
                ('date', models.DateField()),
                ('num_of_available_places', models.IntegerField()),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='bookedride',
            name='ride_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accompanyMe.Ride'),
        ),
    ]
