<<<<<<< HEAD
# Generated by Django 2.1.4 on 2019-01-20 11:27
=======
# Generated by Django 2.1.4 on 2019-01-20 11:03
>>>>>>> 09392c67ada1b9a8d68d05454ede86e59e8b7141

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carsize', models.IntegerField()),
<<<<<<< HEAD
                ('destination', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_email', models.EmailField(max_length=254)),
                ('destination', models.TextField()),
                ('hour', models.TimeField()),
                ('date', models.DateField()),
                ('num_of_available_places', models.IntegerField()),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.DecimalField(decimal_places=9, max_digits=9)),
=======
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> 09392c67ada1b9a8d68d05454ede86e59e8b7141
            ],
        ),
    ]
