# Generated by Django 2.1.4 on 2019-01-20 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accompanyMe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='carsize',
            new_name='phonenumber',
        ),
    ]
