# Generated by Django 2.1.4 on 2019-01-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accompanyMe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('name', 'email', 'phone_number')},
        ),
    ]
